### ISSUE TITLE
class file for com.google.android.gms.internal.zzbck not found

### ISSUE THREAD

**Issue by francisrod01** [googlesamples/android-XYZTouristAttractions#11]
Error:(242, 21) error: cannot access zzbck
class file for com.google.android.gms.internal.zzbck not found

My `Application -> Shared`

```gradle

buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}

apply plugin: 'com.android.library'

repositories {
    jcenter()
    maven {
        url 'https://maven.google.com'
    }
}

dependencies {
    compile 'com.android.support:support-v13:27.0.2'
    compile 'com.google.android.gms:play-services-wearable:11.8.0'
    compile 'com.google.android.gms:play-services-maps:11.8.0'
    compile 'com.google.maps.android:android-maps-utils:0.3.4'
}

// The sample build uses multiple directories to
// keep boilerplate and common code separate from
// the main sample code.
List<String> dirs = [
    'main',     // main sample code; look here for the interesting stuff.
    'common',   // components that are reused by multiple samples
    'template'] // boilerplate code that is generated by the sample template process

android {
        compileSdkVersion 26

    buildToolsVersion "26.0.2"

    defaultConfig {
        minSdkVersion 18
        targetSdkVersion 26
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

    sourceSets {
        main {
            dirs.each { dir ->
                java.srcDirs "src/${dir}/java"
                res.srcDirs "src/${dir}/res"
            }
        }

    }
}
```

**Comment by ybhavesh** [comment]
did you found the fix i am also facing the same issue..

**Comment by codingjeremy** [comment]
Try adding "google()" under jcenter() in the repositories under buildscript. I will do a push to fix it if that resolves it for you. Sorry for the delay!


buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}
...

**Comment by fortunes-technology** [comment]
What's the solution for this? I'm facing similar error. I'm using Cordova Android

**Comment by andreszs** [comment]
Adding `google()` requires Gradle >= 4.1.
If you are using Gradle < 4.1, add Google's maven repository like this instead:

```
repositories {
	jcenter()
	mavenCentral()
	maven {
            url "https://maven.google.com/"
        }
}
```

**Comment by sajawalk** [comment]
Hi,
this is the error message I get.
error: cannot access zzbgl
class file for com.google.android.gms.internal.zzbgl not found
and I have 
apply plugin: 'com.google.gms.google-services'

anyone know a fix?

**Comment by szraksy** [comment]
yeah I got the same problem too, any solution please?

**Comment by yevhenii-borisenko** [comment]
Me too, Anyone solve this problem?

**Comment by ousanmazCT** [comment]
I'm having the same issue for switching the Google Places SDK, getting the Java compiler error "error: cannot access Hide" 

I've gone down many routes in gradle.proporties, running gradle from terminal, updating gradle... but nothing worked.

The moment I add     implementation 'com.google.android.libraries.places:places:1.1.0'     I get the compiler error.

**Comment by caoxu25** [comment]
Please help. I'm having the same issue when add implementation'com.google.android.libraries.places:places:1.1.0' I get the compiler error.
