### ISSUE TITLE
Unable To build Code

### ISSUE THREAD

**Issue by dhaval0122** [googlesamples/android-XYZTouristAttractions#2]
Information:Gradle tasks [clean, :Application:generateDebugSources, :Application:generateDebugTestSources, :Shared:generateDebugSources, :Shared:generateDebugTestSources, :Wearable:generateDebugSources, :Wearable:generateDebugTestSources]
:Application:clean
:Shared:clean
:Wearable:clean UP-TO-DATE
:Application:preBuild
:Application:preDebugBuild
:Application:checkDebugManifest
:Application:preReleaseBuild
:Shared:compileLint
:Shared:copyReleaseLint UP-TO-DATE
:Shared:preBuild
:Shared:preReleaseBuild
:Shared:checkReleaseManifest
:Shared:preDebugBuild
:Shared:preDebugTestBuild
:Shared:prepareComAndroidSupportSupportV42100Library
:Shared:prepareComGoogleAndroidGmsPlayServicesBase6587Library
:Shared:prepareComGoogleAndroidGmsPlayServicesLocation6587Library
:Shared:prepareComGoogleAndroidGmsPlayServicesMaps6587Library
:Shared:prepareComGoogleAndroidGmsPlayServicesWearable6587Library
:Shared:prepareComGoogleMapsAndroidAndroidMapsUtils032Library
:Shared:prepareReleaseDependencies
:Shared:compileReleaseAidl
:Shared:compileReleaseRenderscript
:Shared:generateReleaseBuildConfig
:Shared:generateReleaseAssets UP-TO-DATE
:Shared:mergeReleaseAssets
:Shared:generateReleaseResValues UP-TO-DATE
:Shared:generateReleaseResources
:Shared:mergeReleaseResources
:Shared:processReleaseManifest
:Shared:processReleaseResources
:Shared:generateReleaseSources
:Shared:compileReleaseJava
:Shared:extractReleaseAnnotations
:Shared:mergeReleaseProguardFiles UP-TO-DATE
:Shared:processReleaseJavaRes UP-TO-DATE
:Shared:packageReleaseJar
:Shared:compileReleaseNdk
:Shared:packageReleaseJniLibs UP-TO-DATE
:Shared:packageReleaseLocalJar UP-TO-DATE
:Shared:packageReleaseRenderscript UP-TO-DATE
:Shared:packageReleaseResources
:Shared:bundleRelease
:Application:prepareAndroidXYZTouristAttractionsMasterSharedUnspecifiedLibrary
:Application:prepareComAndroidSupportAppcompatV72103Library
:Application:prepareComAndroidSupportRecyclerviewV72100Library
:Application:prepareComAndroidSupportSupportV132103Library
:Application:prepareComAndroidSupportSupportV42103Library
:Application:prepareComGoogleAndroidGmsPlayServicesBase6587Library
:Application:prepareComGoogleAndroidGmsPlayServicesLocation6587Library
:Application:prepareComGoogleAndroidGmsPlayServicesMaps6587Library
:Application:prepareComGoogleAndroidGmsPlayServicesWearable6587Library
:Application:prepareComGoogleMapsAndroidAndroidMapsUtils032Library
:Application:prepareDebugDependencies
:Application:compileDebugAidl
:Application:compileDebugRenderscript
:Application:generateDebugBuildConfig
:Application:generateDebugAssets UP-TO-DATE
:Application:mergeDebugAssets
:Application:generateDebugResValues UP-TO-DATE
:Application:generateDebugResources
:Application:mergeDebugResources
C:\Users\Downloads\android-XYZTouristAttractions-master(1)\android-XYZTouristAttractions-master\Application\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-xhdpi\abc_ab_share_pack_holo_light.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
C:\Users\Downloads\android-XYZTouristAttractions-master(1)\android-XYZTouristAttractions-master\Application\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\6.5.87\res\drawable-hdpi\common_signin_btn_icon_pressed_dark.9.png ERROR: Unable to open PNG file
C:\Users\Downloads\android-XYZTouristAttractions-master(1)\android-XYZTouristAttractions-master\Application\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\6.5.87\res\drawable-xhdpi\common_signin_btn_icon_pressed_light.9.png ERROR: Unable to open PNG file
Error:Failed to run command:
    D:\AndroidSDK\build-tools\21.1.2\aapt.exe s -i C:\Users\vcsdev0100\Downloads\android-XYZTouristAttractions-master(1)\android-XYZTouristAttractions-master\Application\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\6.5.87\res\drawable-hdpi\common_signin_btn_icon_pressed_dark.9.png -o C:\Users\vcsdev0100\Downloads\android-XYZTouristAttractions-master(1)\android-XYZTouristAttractions-master\Application\build\intermediates\res\debug\drawable-hdpi-v4\common_signin_btn_icon_pressed_dark.9.png
Error Code:
    42
Output:
    C:\Users\Downloads\android-XYZTouristAttractions-master(1)\android-XYZTouristAttractions-master\Application\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\6.5.87\res\drawable-hdpi\common_signin_btn_icon_pressed_dark.9.png ERROR: Unable to open PNG file
:Application:mergeDebugResources FAILED
Error:Execution failed for task ':Application:mergeDebugResources'.

> Error: Failed to run command:
>     D:\AndroidSDK\build-tools\21.1.2\aapt.exe s -i C:\Users\vcsdev0100\Downloads\android-XYZTouristAttractions-master(1)\android-XYZTouristAttractions-master\Application\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\6.5.87\res\drawable-hdpi\common_signin_btn_icon_pressed_dark.9.png -o C:\Users\vcsdev0100\Downloads\android-XYZTouristAttractions-master(1)\android-XYZTouristAttractions-master\Application\build\intermediates\res\debug\drawable-hdpi-v4\common_signin_btn_icon_pressed_dark.9.png
> Error Code:
>     42
> Output:
>     C:\Users\Downloads\android-XYZTouristAttractions-master(1)\android-XYZTouristAttractions-master\Application\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\6.5.87\res\drawable-hdpi\common_signin_btn_icon_pressed_dark.9.png ERROR: Unable to open PNG file

**Comment by FedericoPonzi** [comment]
Well, i printed a much longer error but basically we have the same problem : `-common_signin_btn_icon_focus_dark.9.png ERROR: Unable to open PNG file`
Lets wait for some answer.

**Comment by adamkoch** [comment]
Not too sure what's going on here. Can you try opening that png and see if it loads correctly and is indeed a png?

Seems [others](http://stackoverflow.com/questions/23366222/libpng-error-not-a-png-file-error-showing-in-android-studio) have had this issue when the png file was somehow not a png (jpg or some other format).

However I have no idea how this happened for a png that is part of Play Services. I'm on Mac and did a fresh clone and build and it worked fine.

**Comment by FedericoPonzi** [comment]
![common_signin_btn_icon_focus_light 9](https://cloud.githubusercontent.com/assets/2124904/7317786/ce101b74-ea84-11e4-99ab-f66adb3c694d.png)

**Comment by FedericoPonzi** [comment]
In my case i can't edit the file since its inside the build path.
I've tried to ridownload the whole project, and install build tools 21.1.2 and now the error is the same but with another file in that directory.

**Comment by adamkoch** [comment]
I gather both of you are on Windows? Maybe it's the build path length getting too long?
http://stackoverflow.com/questions/24875555/android-studio-wear-app-error-unable-to-open-png

Try moving up a level or two or renaming "android-XYZTouristAttractions-master" to "xyz" or some such to reduce path length.

**Comment by FedericoPonzi** [comment]
As i said in my issue thread, yes i'm on windows! Gonna try it know and let you know asap. Thanks for support

**Comment by FedericoPonzi** [comment]
Working to me! Thanks a lot (the app is great!)

**Comment by adamkoch** [comment]
No probs :)

**Comment by dhaval0122** [comment]
sorry for late replay, I have MAC i have tried to modify image but not working (First time i have download code as zip from git hub & open using .iml file)

i have tried another way

Android Studio --> File --> import sample

its working.
