### ISSUE TITLE
"maximum recursion depth exceeded while calling a Python object" when running generate_docs.py

### ISSUE THREAD

**Issue by 2hamed** [googlesamples/android-XYZTouristAttractions#4]
I tried to run the `generate_docs.py` but I encountered the following error.

>   return docs.generate_docs.main()
>  File "E:\dev\android\apps\android-play-games-in-motion\docs\generate_docs.py", line 36, in main
>    '--source-dir', os.path.join(THIS_DIR, 'src'),
>  File "C:\Python34\lib\ntpath.py", line 108, in join
>    result_drive, result_path = splitdrive(path)
>  File "C:\Python34\lib\ntpath.py", line 158, in splitdrive
>    empty = _get_empty(p)
>  File "C:\Python34\lib\ntpath.py", line 36, in _get_empty
>    if isinstance(path, bytes):
> RuntimeError: maximum recursion depth exceeded while calling a Python object

**Comment by adamkoch** [comment]
I think you meant to file this over in the android-play-games-in-motion repo?
https://github.com/googlesamples/android-play-games-in-motion/issues

**Comment by 2hamed** [comment]
Oops, I'm sorry.
I don't know how this happened.
My mistake.
