### ISSUE TITLE
Double tap opens two "detail views" and icon is lost as a result

### ISSUE THREAD

**Issue by lanzelot1989** [googlesamples/android-XYZTouristAttractions#5]
See the [gif](http://giphy.com/gifs/l41lSVl75kyy5NWp2). 

I got the behavior on the third try because I performed the actions on the emulator.

This can easily be reproduced on a real device by double tapping a list view entry.

As a result, the detail view opens twice and after tapping "back" two times, the picture is gone.

**Comment by adamkoch** [comment]
Fixed in latest push.
