### ISSUE TITLE
error: package com.google.android.gms.maps.model does not exist

### ISSUE THREAD

**Issue by alekwo** [googlesamples/android-XYZTouristAttractions#9]
I was using this sample several times already with not issues. 

But recently, when I create a new project using this sample, it won't compile because of errors in:

\Shared\src\main\java\com\example\android\xyztouristattractions\common\Attraction.java
Error:(22, 41) error: package com.google.android.gms.maps.model does not exist

\Shared\src\main\java\com\example\android\xyztouristattractions\common\Utils.java
Error:(33, 41) error: package com.google.android.gms.maps.model does not exist

Not nice as for a sample ;-)

**Comment by michelangelomo** [comment]
Remove "compile 'com.google.maps.android:android-maps-utils:0.3.4'" from **Application dependencies**.
Add "classpath 'com.google.gms:google-services:3.0.0'" under **Shared > buildscript > dependencies**.

**Comment by codingjeremy** [comment]
There is an update planned for early this year, so a fix should be merged soon. Sorry about that!

**Comment by toFlash** [comment]
I cant fix this issue (

**Comment by alekwo** [comment]
I looked for the differences with the project I created a few months ago (which worked). 

The quick workaround is to change the version of gms:play-services in all three (Application, Shared, Wereable) gradle build files:

Change the version from 10.0.1
    compile 'com.google.android.gms:play-services-location:10.0.1'
    compile 'com.google.android.gms:play-services-wearable:10.0.1'
 to 8.4.0:
    compile 'com.google.android.gms:play-services-location:8.4.0'
    compile 'com.google.android.gms:play-services-wearable:8.4.0'

And app shall work.

**Comment by codingjeremy** [comment]
You can still use 10.0.1. It's just some of the classes shifted around.

In both the "Shared" and "Wearable" modules, edit the 'dependencies' in the build.gradle. Switch out the line below in both. (Don't do anything to the "Application" build.gradle.)

compile 'com.google.android.gms:play-services-location:10.0.1'
to
compile 'com.google.android.gms:play-services-maps:10.0.1'

**Comment by toFlash** [comment]
> compile 'com.google.android.gms:play-services-location:10.0.1'
> to
> compile 'com.google.android.gms:play-services-maps:10.0.1'

works for me! thanks!!

**Comment by zfowles** [comment]
Thank you @codingjeremy! 

To others, don't change anything other than what codingjeremy said or you will cause more issues.

**Comment by codingjeremy** [comment]
This has now been resolved in the sample.
